### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by M-Yamashita01** [M-Yamashita01/mynote#9]
- [x] Introduce Air to build Golang automatically.
- [x] Register article in home page
- [x] Show articles that are registered by a user
- [ ] Search articles by using the title or category or summary.
- [ ] Set category to the article when the article is registered.
- [ ] Create the summary for the article when the article is registered.
- [ ] Edit categories.
- [ ] Edit summary.
- [x] Introduce Vue.js and Nuxt.js.
